const data = [
  {
    "date": "1907-01-26",
    "country": "CZ",
    "CZtitle": "Volební právo mužů",
    "CZdescription": "<i>26. ledna 1907</i> – všeobecné, tajné a rovné vol. právo (pro muže)",
    "ENtitle": "Male Suffrage",
    "ENdescription": "<i>January 26, 1907</i> – universal, secret and equal voting rights (for men)",
    "DEtitle": "Männerwahlrecht",
    "DEdescription": "26. Januar 1907 – allgemeines, geheimes und gleiches Wahlrecht (für Männer)",
    "url": "male-suffrage"
  },
  {
    "date": "1914-07-25",
    "country": "CZ",
    "CZtitle": "Stanné právo",
    "CZdescription": "<i>25. července 1914</i> – vyhlášení stanného práva po atentátu v Sarajevu na následníka trůnu; omezení občanských svobod a parlamentarismu",
    "ENtitle": "Martial Law",
    "ENdescription": "<i>July 25, 1914</i> – declaration of martial law after the assassination of the heir to the throne in Sarajevo, restriction of civil freedoms and parliamentarism",
    "DEtitle": "Standrecht",
    "DEdescription": "25. Juli 1914 – Verkündung des Standrechts nach dem Attentat auf den Thronfolger in Sarajewo, Einschränkung der bürgerlichen Freiheiten und des Parlamentarismus",
    "url": "martial-law"
  },
  {
    "date": "1917-05-30",
    "country": "CZ",
    "CZtitle": "Pol. ústupky",
    "CZdescription": "<i>30. květen 1917</i> – obnovení parlamentarismu (Říšské rady) a zmírnění politické represe",
    "ENtitle": "Political Concessions",
    "ENdescription": "<i>May 30, 1917</i> – restoration of parliamentarism (Imperial Council) and relaxation of political repression",
    "DEtitle": "Politische Zugeständnisse",
    "DEdescription": "30. Mai 1917 – Wiederherstellung des Parlamentarismus (Reichsrat) und Lockerung der politischen Repression",
    "url": "political-concessions"
  },
  {
    "date": "1918-10-28",
    "country": "CZ",
    "CZtitle": "Vznik ČSR",
    "CZdescription": "<i>28. říjen 1918</i> – vznik samostatné Československé republiky",
    "ENtitle": "Formation of Czechoslovakia",
    "ENdescription": "<i>October 28, 1918</i> – the establishment of the independent Czechoslovak Republic",
    "DEtitle": "Gründung der Tschechoslowakei",
    "DEdescription": "28. Oktober 1918 – Gründung der unabhängigen Tschechoslowakischen Republik",
    "url": "formation-of-czechoslovakia"
  },
  {
    "date": "1918-11-13",
    "country": "CZ",
    "CZtitle": "Prozatímní ústava",
    "CZdescription": "<i>13. listopadu 1918</i> – schválení prozatímní ústavy (vol. právo žen)",
    "ENtitle": "Interim Constitution",
    "ENdescription": "<i>November 13, 1918</i> – approval of the interim constitution (women's suffrage)",
    "DEtitle": "Übergangsverfassung",
    "DEdescription": "13. November 1918 – Verabschiedung der Übergangsverfassung (Frauenwahlrecht)",
    "url": "interim-constitution"
  },
  {
    "date": "1918-11-14",
    "country": "CZ",
    "CZtitle": "Rev. národní shromáždění",
    "CZdescription": "<i>14. listopadu 1918</i> – vznik Revolučního národního shromáždění, Masaryk prezidentem",
    "ENtitle": "Rev. National Assembly",
    "ENdescription": "<i>November 14, 1918</i> – establishment of the Revolutionary National Assembly, Masaryk as president",
    "DEtitle": "Rev. Nationalversammlung",
    "DEdescription": "14. November 1918 – Gründung der Revolutionären Nationalversammlung, Masaryk zum Präsidenten",
    "url": "revolutionary-national-assembly"
  },
  {
    "date": "1918-12-19",
    "country": "CZ",
    "CZtitle": "Sociální zákony",
    "CZdescription": "<i>19. prosince 1918</i> – zákony o 8hodinové pracovní době, pozemkové reformě, sociálním pojištění dělníků",
    "ENtitle": "Social Laws",
    "ENdescription": "<i>December 19, 1918</i> – laws on the 8-hour working day, land reform, and workers' social insurance",
    "DEtitle": "Sozialgesetze",
    "DEdescription": "19. Dezember 1918 – Gesetze über den 8-Stunden-Arbeitstag, Bodenreform und Sozialversicherung für Arbeiter",
    "url": "social-laws"
  },
  {
    "date": "1919-01-23",
    "country": "CZ",
    "CZtitle": "Válka o Těšínsko",
    "CZdescription": "<i>23. ledna 1919</i> – československo-polské boje o Těšínsko (sedmidenní válka)",
    "ENtitle": "War over Teschen",
    "ENdescription": "<i>January 23, 1919</i> – Czechoslovak-Polish war over Teschen (seven-day war)",
    "DEtitle": "Krieg um Teschen",
    "DEdescription": "23. Januar 1919 – Tschechoslowakisch-polnischer Krieg um Teschen (Siebentageskrieg)",
    "url": "war-over-teschen"
  },
  {
    "date": "1919-04-27",
    "country": "CZ",
    "CZtitle": "Válka o Slovensko",
    "CZdescription": "<i>27. dubna 1919</i> – maďarsko-československá válka o Slovensko",
    "ENtitle": "War over Slovakia",
    "ENdescription": "<i>April 27, 1919</i> – Hungarian-Czechoslovak war over Slovakia",
    "DEtitle": "Krieg um die Slowakei",
    "DEdescription": "27. April 1919 – Ungarisch-Tschechoslowakischer Krieg um die Slowakei",
    "url": "war-over-slovakia"
  },
  {
    "date": "1919-06-15",
    "country": "CZ",
    "CZtitle": "Komunální volby",
    "CZdescription": "<i>15. června 1919</i> – komunální volby, ženy mohou poprvé volit a být voleny",
    "ENtitle": "Local Elections",
    "ENdescription": "<i>June 15, 1919</i> – local elections, women can vote and be elected for the first time",
    "DEtitle": "Kommunalwahlen",
    "DEdescription": "15. Juni 1919 – Kommunalwahlen, Frauen dürfen zum ersten Mal wählen und gewählt werden",
    "url": "local-elections-women"
  },
  {
    "date": "1920-02-29",
    "country": "CZ",
    "CZtitle": "Finální ústava (rovnost žen)",
    "CZdescription": "<i>29. února 1920</i> – schválení finální ústavy ČSR (rovnoprávnost žen)",
    "ENtitle": "Final Constitution",
    "ENdescription": "<i>February 29, 1920</i> – approval of the final constitution of Czechoslovakia (equality of women)",
    "DEtitle": "Endgültige Verfassung",
    "DEdescription": "29. Februar 1920 – Verabschiedung der endgültigen Verfassung der ČSR (Gleichberechtigung der Frauen)",
    "url": "final-constitution"
  },
  {
    "date": "1920-04-18",
    "country": "CZ",
    "CZtitle": "Volby do posl. sněmovny",
    "CZdescription": "<i>18. dubna 1920</i> – volby do poslanecké sněmovny, za týden do senátu",
    "ENtitle": "Chamber of Deputies Elections",
    "ENdescription": "<i>April 18, 1920</i> – elections to the Chamber of Deputies, Senate elections a week later",
    "DEtitle": "Abgeordnetenhauswahlen",
    "DEdescription": "18. April 1920 – Wahlen zum Abgeordnetenhaus, eine Woche später Senatswahlen",
    "url": "chamber-of-deputies-elections"
  },
  {
    "date": "1923-03-19",
    "country": "CZ",
    "CZtitle": "Omezení extrem. stran",
    "CZdescription": "<i>19. března 1923</i> – zákon na ochranu republiky (omezení extremistických stran)",
    "ENtitle": "Restriction of Extrem. Parties",
    "ENdescription": "<i>March 19, 1923</i> – Act for the Protection of the Republic (restriction of extremist parties)",
    "DEtitle": "Einschränkung extrem. Parteien",
    "DEdescription": "19. März 1923 – Gesetz zum Schutz der Republik (Einschränkung extremistischer Parteien)",
    "url": "restriction-of-extremist-parties"
  },
  {
    "date": "1933-02-15",
    "country": "CZ",
    "CZtitle": "Hospodářská krize",
    "CZdescription": "<i>15. února 1933</i> – vrchol hospodářské krize v ČSR",
    "ENtitle": "Economic Crisis",
    "ENdescription": "<i>February 15, 1933</i> – peak of economic crisis in Czechoslovakia",
    "DEtitle": "Wirtschaftskrise",
    "DEdescription": "15. Februar 1933 – Höhepunkt der Wirtschaftskrise in der ČSR",
    "url": "economic-crisis-cz"
  },
  {
    "date": "1933-10-04",
    "country": "CZ",
    "CZtitle": "Zákaz nacistické strany",
    "CZdescription": "<i>4. října 1933</i> – rozpuštění nacistické strany DNSAP v ČSR",
    "ENtitle": "Ban on Nazi Party",
    "ENdescription": "<i>October 4, 1933</i> – dissolution of the DNSAP Nazi party in Czechoslovakia",
    "DEtitle": "Verbot der Nazipartei",
    "DEdescription": "4. Oktober 1933 – Auflösung der Nazi-Partei DNSAP in der ČSR",
    "url": "ban-on-nazi-party"
  },
  {
    "date": "1935-05-16",
    "country": "CZ",
    "CZtitle": "Obranná smlouva s SSSR",
    "CZdescription": "<i>16. května 1935</i> – československo-sovětská smlouva o vojenské spolupráci",
    "ENtitle": "Soviet Defense Treaty",
    "ENdescription": "<i>May 16, 1935</i> – Czechoslovak-Soviet treaty on military cooperation",
    "DEtitle": "Sowjetischer Verteidigungspakt",
    "DEdescription": "16. Mai 1935 – Tschechoslowakisch-sowjetischer Vertrag über militärische Zusammenarbeit",
    "url": "soviet-defense-treaty"
  },
  {
    "date": "1935-12-18",
    "country": "CZ",
    "CZtitle": "Beneš prezidentem",
    "CZdescription": "<i>18. prosince 1935</i> – Edvard Beneš zvolen prezidentem",
    "ENtitle": "Beneš as President",
    "ENdescription": "<i>December 18, 1935</i> – Edvard Beneš elected president",
    "DEtitle": "Beneš als Präsident",
    "DEdescription": "18. Dezember 1935 – Edvard Beneš zum Präsidenten gewählt",
    "url": "benes-as-president"
  },
  {
    "date": "1936-05-13",
    "country": "CZ",
    "CZtitle": "Zákon o obraně státu",
    "CZdescription": "<i>13. května 1936</i> – zákon o obraně státu (reakce na nacistickou hrozbu)",
    "ENtitle": "State Defense Act",
    "ENdescription": "<i>May 13, 1936</i> – State Defense Act (reaction to the Nazi threat)",
    "DEtitle": "Staatsverteidigungsgesetz",
    "DEdescription": "13. Mai 1936 – Staatsverteidigungsgesetz (Reaktion auf die Bedrohung durch die Nazis)",
    "url": "state-defense-act"
  },
  {
    "date": "1937-09-14",
    "country": "CZ",
    "CZtitle": "Masarykova smrt",
    "CZdescription": "<i>14. září 1937</i> – smrt Tomáše Garrigua Masaryka",
    "ENtitle": "Death of Masaryk",
    "ENdescription": "<i>September 14, 1937</i> – death of Tomáš Garrigue Masaryk",
    "DEtitle": "Masaryks Tod",
    "DEdescription": "14. September 1937 – Tod von Tomáš Garrigue Masaryk",
    "url": "masaryk-death"
  },
  {
    "date": "1938-09-12",
    "country": "CZ",
    "CZtitle": "Sudetoněmecké povstání",
    "CZdescription": "<i>12. září 1938</i> – povstání sudetských Němců podporovaných nacistickým Německem",
    "ENtitle": "Sudeten German Uprising",
    "ENdescription": "<i>September 12, 1938</i> – uprising of Sudeten Germans supported by Nazi Germany",
    "DEtitle": "Aufstand der Sudetendeutschen",
    "DEdescription": "12. September 1938 – Aufstand der Sudetendeutschen, unterstützt durch Nazi-Deutschland",
    "url": "sudeten-german-uprising"
  },
  {
    "date": "1938-09-23",
    "country": "CZ",
    "CZtitle": "Všeobecná mobilizace",
    "CZdescription": "<i>23. září 1938</i> – vyhlášení všeobecné mobilizace",
    "ENtitle": "General Mobilization",
    "ENdescription": "<i>September 23, 1938</i> – declaration of general mobilization",
    "DEtitle": "Allgemeine Mobilisierung",
    "DEdescription": "23. September 1938 – Ausrufung der allgemeinen Mobilisierung",
    "url": "general-mobilization"
  },
  {
    "date": "1938-09-29",
    "country": "CZ",
    "CZtitle": "Mnichovská dohoda",
    "CZdescription": "<i>29.–30. září 1938</i> – Mnichovská dohoda, ČSR nucena postoupit Sudety, vznik Česko-Slovenské republiky",
    "ENtitle": "Munich Agreement",
    "ENdescription": "<i>September 29–30, 1938</i> – Munich Agreement, Czechoslovakia forced to cede the Sudetenland, creation of the Czecho-Slovak Republic",
    "DEtitle": "Münchner Abkommen",
    "DEdescription": "29.–30. September 1938 – Münchner Abkommen, ČSR gezwungen, das Sudetenland abzutreten, Gründung der Tschecho-Slowakischen Republik",
    "url": "munich-agreement"
  },
  {
    "date": "1939-03-14",
    "country": "CZ",
    "CZtitle": "Odtržení Slovenska",
    "CZdescription": "<i>14. března 1939</i> – vyhlášení samostatného Slovenského štátu",
    "ENtitle": "Secession of Slovakia",
    "ENdescription": "<i>March 14, 1939</i> – declaration of the independent Slovak State",
    "DEtitle": "Abspaltung der Slowakei",
    "DEdescription": "14. März 1939 – Ausrufung des unabhängigen slowakischen Staates",
    "url": "secession-of-slovakia"
  },
  {
    "date": "1939-03-15",
    "country": "CZ",
    "CZtitle": "Okupace Čech a Moravy",
    "CZdescription": "<i>15. března 1939</i> – okupace zbytku Čech a Moravy",
    "ENtitle": "Bohemia and Moravia occupation",
    "ENdescription": "<i>March 15, 1939</i> – occupation of the rest of Bohemia and Moravia",
    "DEtitle": "Besetzung Böhmens und Mährens",
    "DEdescription": "15. März 1939 – Besetzung der restlichen böhmischen und mährischen Gebiete",
    "url": "occupation-end-of-csr"
  },


  {
    "date": "1914-07-31",
    "country": "DE",
    "CZtitle": "Cenzura a omezení svobod",
    "CZdescription": "<i>31. července 1914</i> – cenzura tisku a omezení shromažďování po vyhlášení válečného stavu",
    "ENtitle": "Restriction of Freedoms",
    "ENdescription": "<i>July 31, 1914</i> – press censorship and restriction of assembly after the declaration of martial law",
    "DEtitle": "Freiheiteneinschränkung",
    "DEdescription": "31. Juli 1914 – Pressezensur und Versammlungsbeschränkungen nach der Ausrufung des Kriegszustands",
    "url": "censorship-and-restriction-of-freedoms"
  },
  {
    "date": "1916-08-29",
    "country": "DE",
    "CZtitle": "Vojenská diktatura",
    "CZdescription": "<i>29. srpna 1916</i> – Hindenburg a Ludendorff přebírají faktickou moc (vojenská diktatura)",
    "ENtitle": "Military Dictatorship",
    "ENdescription": "<i>August 29, 1916</i> – Hindenburg and Ludendorff take factual power (military dictatorship)",
    "DEtitle": "Militärdiktatur",
    "DEdescription": "29. August 1916 – Hindenburg und Ludendorff übernehmen die faktische Macht (Militärdiktatur)",
    "url": "military-dictatorship"
  },
  {
    "date": "1918-01-28",
    "country": "DE",
    "CZtitle": "Stávky dělníků za svobodu",
    "CZdescription": "<i>od ledna 1918</i> – masové stávky dělníků za mír a politické svobody",
    "ENtitle": "Workers' Strikes for Freedom",
    "ENdescription": "<i>From January 1918</i> – mass strikes by workers for peace and political freedoms",
    "DEtitle": "Arbeiterstreiks für Freiheit",
    "DEdescription": "Ab Januar 1918 – Massenstreiks der Arbeiter für Frieden und politische Freiheiten",
    "url": "workers-strikes-for-freedom"
  },
  {
    "date": "1918-11-09",
    "country": "DE",
    "CZtitle": "Vyhlášení republiky",
    "CZdescription": "<i>9. listopadu 1918</i> – abdikace Viléma II., vyhlášení republiky",
    "ENtitle": "Proclamation of the Republic",
    "ENdescription": "<i>November 9, 1918</i> – abdication of Wilhelm II, proclamation of the republic",
    "DEtitle": "Ausrufung der Republik",
    "DEdescription": "9. November 1918 – Abdankung Wilhelms II., Ausrufung der Republik",
    "url": "proclamation-of-the-republic"
  },
  {
    "date": "1918-11-12",
    "country": "DE",
    "CZtitle": "8h pracovní doba",
    "CZdescription": "<i>12. listopadu 1918</i> – zavedení 8hodinové pracovní doby",
    "ENtitle": "8-hour Work Day",
    "ENdescription": "<i>November 12, 1918</i> – introduction of the 8-hour working day",
    "DEtitle": "8-Stunden-Arbeitstag",
    "DEdescription": "12. November 1918 – Einführung des 8-Stunden-Arbeitstages",
    "url": "8-hour-work-day-de"
  },
  {
    "date": "1919-01-05",
    "country": "DE",
    "CZtitle": "Povstání spartakovců",
    "CZdescription": "<i>5. - 15. ledna 1919</i> – potlačení Spartakovského povstání, zavraždění Karla Liebknechta a Rosy Luxemburgové",
    "ENtitle": "Spartacist Uprising",
    "ENdescription": "<i>January 5–15, 1919</i> – suppression of the Spartacist uprising, assassination of Karl Liebknecht and Rosa Luxemburg",
    "DEtitle": "Spartakusaufstand",
    "DEdescription": "5.–15. Januar 1919 – Niederschlagung des Spartakusaufstands, Ermordung von Karl Liebknecht und Rosa Luxemburg",
    "url": "spartacist-uprising"
  },
  {
    "date": "1919-01-19",
    "country": "DE",
    "CZtitle": "Volby vč. žen",
    "CZdescription": "<i>19. ledna 1919</i> – volby do Výmarského nár. shromáždění (i ženy)",
    "ENtitle": "Elections including Women",
    "ENdescription": "<i>January 19, 1919</i> – elections to the Weimar National Assembly (including women)",
    "DEtitle": "Wahlen einschließlich Frauen",
    "DEdescription": "19. Januar 1919 – Wahlen zur Weimarer Nationalversammlung (einschließlich Frauen)",
    "url": "elections-including-women"
  },
  {
    "date": "1919-08-11",
    "country": "DE",
    "CZtitle": "Výmarská ústava",
    "CZdescription": "<i>11. srpna 1919</i> – přijetí Výmarské ústavy (základní občanská práva)",
    "ENtitle": "Weimar Constitution",
    "ENdescription": "<i>August 11, 1919</i> – adoption of the Weimar Constitution (fundamental civil rights)",
    "DEtitle": "Weimarer Verfassung",
    "DEdescription": "11. August 1919 – Verabschiedung der Weimarer Verfassung (Grundrechte)",
    "url": "weimar-constitution"
  },
  {
    "date": "1920-01-18",
    "country": "DE",
    "CZtitle": "Závodní rady",
    "CZdescription": "<i>18. ledna 1920</i> – zákon o závodních radách (zastoupení dělníků)",
    "ENtitle": "Works Councils",
    "ENdescription": "<i>January 18, 1920</i> – Works Councils Act (worker representation)",
    "DEtitle": "Betriebsräte",
    "DEdescription": "18. Januar 1920 – Betriebsrätegesetz (Arbeitnehmervertretung)",
    "url": "works-councils"
  },
  {
    "date": "1923-01-11",
    "country": "DE",
    "CZtitle": "Okupace Porýní",
    "CZdescription": "<i>11. ledna 1923</i> – okupace Porýní",
    "ENtitle": "Occupation of the Rhineland",
    "ENdescription": "<i>January 11, 1923</i> – occupation of the Rhineland",
    "DEtitle": "Besetzung des Ruhrgebiets",
    "DEdescription": "11. Januar 1923 – Besetzung des Ruhrgebiets",
    "url": "occupation-rhineland"
  },
  {
    "date": "1923-11-01",
    "country": "DE",
    "CZtitle": "Hyperinflace",
    "CZdescription": "<i>Listopad 1923</i> – hyperinflace (vrchol)",
    "ENtitle": "Hyperinflation",
    "ENdescription": "<i>November 1923</i> – hyperinflation (peak)",
    "DEtitle": "Hyperinflation",
    "DEdescription": "November 1923 – Hyperinflation (Höhepunkt)",
    "url": "hyperinflation"
  },
  {
    "date": "1923-11-08",
    "country": "DE",
    "CZtitle": "Pivní puč",
    "CZdescription": "<i>8.–9. listopadu 1923</i> – Pivní puč v Mnichově",
    "ENtitle": "Beer Hall Putsch",
    "ENdescription": "<i>November 8–9, 1923</i> – Beer Hall Putsch in Munich",
    "DEtitle": "Hitlerputsch",
    "DEdescription": "8.–9. November 1923 – Hitlerputsch in München",
    "url": "beer-hall-putsch"
  },
  {
    "date": "1924-08-30",
    "country": "DE",
    "CZtitle": "Dawesův plán",
    "CZdescription": "<i>30. srpna 1924</i> – Dawesův plán poskytl Německu ohromné půjčky z USA, díky nimž došlo k stabilizaci ekonomiky a oslabení nacistů",
    "ENtitle": "Dawes Plan",
    "ENdescription": "<i>August 30, 1924</i> – the Dawes Plan provided Germany with enormous loans from the USA, which stabilized the economy and weakened the Nazis",
    "DEtitle": "Dawes-Plan",
    "DEdescription": "30. August 1924 – der Dawes-Plan gewährte Deutschland enorme Kredite aus den USA, die die Wirtschaft stabilisierten und die Nazis schwächten",
    "url": "dawes-plan"
  },
  {
    "date": "1925-12-01",
    "country": "DE",
    "CZtitle": "Locarnské dohody",
    "CZdescription": "<i>1. prosince 1925</i> – Locarnské dohody garantovaly neporušitelnost západních hranic Německa; východní ponechaly bez mezinárodních záruk",
    "ENtitle": "Locarno Treaties",
    "ENdescription": "<i>December 1, 1925</i> – the Locarno Treaties guaranteed the inviolability of Germany's western borders; eastern borders were left without international guarantees",
    "DEtitle": "Locarno-Verträge",
    "DEdescription": "1. Dezember 1925 – die Locarno-Verträge garantierten die Unverletztheit der Westgrenzen Deutschlands; die Ostgrenzen wurden ohne internationale Garantien belassen",
    "url": "locarno-treaties"
  },
  {
    "date": "1926-09-08",
    "country": "DE",
    "CZtitle": "Německo členem SN",
    "CZdescription": "<i>8. září 1926</i> – přijetí Německa do Společnosti národů",
    "ENtitle": "Admission to League of Nations",
    "ENdescription": "<i>September 8, 1926</i> – admission of Germany to the League of Nations",
    "DEtitle": "Aufnahme in den Völkerbund",
    "DEdescription": "8. September 1926 – Aufnahme Deutschlands in den Völkerbund",
    "url": "germany-league-of-nations"
  },
  {
    "date": "1932-04-01",
    "country": "DE",
    "CZtitle": "Hospodářská krize",
    "CZdescription": "<i>Duben 1932</i> – vrchol hospodářské krize v Německu (6 milionů nezaměstnaných)",
    "ENtitle": "Economic Crisis",
    "ENdescription": "<i>April 1932</i> – peak of economic crisis in Germany (6 million unemployed)",
    "DEtitle": "Wirtschaftskrise",
    "DEdescription": "April 1932 – Höhepunkt der Wirtschaftskrise in Deutschland (6 Millionen Arbeitslose)",
    "url": "economic-crisis-de"
  },
  {
    "date": "1933-01-30",
    "country": "DE",
    "CZtitle": "Hitler kancléřem",
    "CZdescription": "<i>30. ledna 1933</i> – Hitler jmenován říšským kancléřem",
    "ENtitle": "Hitler as Chancellor",
    "ENdescription": "<i>January 30, 1933</i> – Hitler appointed Reich Chancellor",
    "DEtitle": "Hitler als Reichskanzler",
    "DEdescription": "30. Januar 1933 – Hitler wird zum Reichskanzler ernannt",
    "url": "hitler-as-chancellor"
  },
  {
    "date": "1933-02-27",
    "country": "DE",
    "CZtitle": "Požár Reichstagu",
    "CZdescription": "<i>27. února 1933</i> – požár Reichstagu",
    "ENtitle": "Reichstag Fire",
    "ENdescription": "<i>February 27, 1933</i> – Reichstag fire",
    "DEtitle": "Reichstagsbrand",
    "DEdescription": "27. Februar 1933 – Reichstagsbrand",
    "url": "reichstag-fire"
  },
  {
    "date": "1933-02-28",
    "country": "DE",
    "CZtitle": "Zrušení občanských svobod",
    "CZdescription": "<i>28. února 1933</i> – Hindenburgův dekret o zrušení základních občanských svobod",
    "ENtitle": "Abolition of Civil Liberties",
    "ENdescription": "<i>February 28, 1933</i> – Hindenburg Decree on the abolition of fundamental civil liberties",
    "DEtitle": "Freiheiteneinschränkung",
    "DEdescription": "28. Februar 1933 – Hindenburg-Dekret über die Aufhebung der bürgerlichen Grundrechte",
    "url": "abolition-of-civil-liberties"
  },
  {
    "date": "1933-03-23",
    "country": "DE",
    "CZtitle": "Zmocňovací zákon",
    "CZdescription": "<i>23. března 1933</i> – zmocňovací zákon, konec parlamentní demokracie",
    "ENtitle": "Enabling Act",
    "ENdescription": "<i>March 23, 1933</i> – Enabling Act, end of parliamentary democracy",
    "DEtitle": "Ermächtigungsgesetz",
    "DEdescription": "23. März 1933 – Ermächtigungsgesetz, Ende der parlamentarischen Demokratie",
    "url": "enabling-act"
  },
  {
    "date": "1933-02-29",
    "country": "DE",
    "CZtitle": "Zákaz odborů a opozice",
    "CZdescription": "<i>28. února – 14. července 1933</i> – zákaz odborů a opozičních stran",
    "ENtitle": "Ban on Unions and Opposition",
    "ENdescription": "<i>February 28 – July 14, 1933</i> – ban on trade unions and opposition parties",
    "DEtitle": "Gewerksch. und Opposit. Verbot",
    "DEdescription": "28. Februar – 14. Juli 1933 – Verbot von Gewerkschaften und Oppositionsparteien",
    "url": "ban-on-unions-and-opposition"
  },
  {
    "date": "1934-06-30",
    "country": "DE",
    "CZtitle": "Noc dlouhých nožů",
    "CZdescription": "<i>30. června – 2. července 1934</i> – Noc dlouhých nožů, likvidace vnitřní opozice",
    "ENtitle": "Night of the Long Knives",
    "ENdescription": "<i>June 30 – July 2, 1934</i> – Night of the Long Knives, elimination of internal opposition",
    "DEtitle": "Nacht der langen Messer",
    "DEdescription": "30. Juni – 2. Juli 1934 – Nacht der langen Messer, Liquidierung der internen Opposition",
    "url": "night-of-the-long-knives"
  },
  {
    "date": "1934-08-02",
    "country": "DE",
    "CZtitle": "Hitler Führerem",
    "CZdescription": "<i>2. srpna 1934</i> – smrt Hindenburga, Hitler spojuje funkce kancléře a prezidenta",
    "ENtitle": "Hitler as Fuhrer",
    "ENdescription": "<i>August 2, 1934</i> – death of Hindenburg, Hitler combines the offices of chancellor and president",
    "DEtitle": "Hitler als Führer",
    "DEdescription": "2. August 1934 – Hindenburgs Tod, Hitler vereint die Ämter des Kanzlers und des Präsidenten",
    "url": "hitler-as-fuhrer"
  },
  {
    "date": "1935-09-15",
    "country": "DE",
    "CZtitle": "Norimberské zákony",
    "CZdescription": "<i>15. září 1935</i> – Norimberské zákony (rasová diskriminace Židů)",
    "ENtitle": "Nuremberg Laws",
    "ENdescription": "<i>September 15, 1935</i> – Nuremberg Laws (racial discrimination of Jews)",
    "DEtitle": "Nürnberger Gesetze",
    "DEdescription": "15. September 1935 – Nürnberger Gesetze (Rassendiskriminierung von Juden)",
    "url": "nuremberg-laws"
  },
  {
    "date": "1938-03-12",
    "country": "DE",
    "CZtitle": "Anschluss Rakouska",
    "CZdescription": "<i>12. března 1938</i> – anexe Rakouska",
    "ENtitle": "Anschluss of Austria",
    "ENdescription": "<i>March 12, 1938</i> – annexation of Austria",
    "DEtitle": "Anschluss Österreichs",
    "DEdescription": "12. März 1938 – Anschluss Österreichs",
    "url": "anschluss-of-austria"
  },
  {
    "date": "1938-11-09",
    "country": "DE",
    "CZtitle": "Křišťálová noc",
    "CZdescription": "<i>9.–10. listopadu 1938</i> – Křišťálová noc, pogromy na Židy",
    "ENtitle": "Kristallnacht",
    "ENdescription": "<i>November 9–10, 1938</i> – Kristallnacht, pogroms against Jews",
    "DEtitle": "Kristallnacht",
    "DEdescription": "9.–10. November 1938 – Kristallnacht, Pogrome gegen Juden",
    "url": "kristallnacht-de"
  }
];